// src/modules/notifications/notification.events.js

module.exports = {
  // Proposal - user
  PROPOSAL_SUBMITTED_UNPAID: 'PROPOSAL_SUBMITTED_UNPAID',
  PROPOSAL_PAYMENT_REMINDER_TPLUS3: 'PROPOSAL_PAYMENT_REMINDER_TPLUS3',
  PROPOSAL_UNPAID_EXPIRED: 'PROPOSAL_UNPAID_EXPIRED',
  // PROPOSAL_SUBMITTED_PAID: 'PROPOSAL_SUBMITTED_PAID',
  PROPOSAL_PAYMENT_CONFIRMED_REVIEW_PENDING: 'PROPOSAL_PAYMENT_CONFIRMED_REVIEW_PENDING',
  PROPOSAL_REUPLOAD_REQUIRED: 'PROPOSAL_REUPLOAD_REQUIRED',
  PROPOSAL_REJECTED_REFUND_INITIATED: 'PROPOSAL_REJECTED_REFUND_INITIATED', // combined

  // Proposal - admin
  ADMIN_PROPOSAL_SUBMITTED_UNPAID: 'ADMIN_PROPOSAL_SUBMITTED_UNPAID',
  // ADMIN_PROPOSAL_SUBMITTED_PAID: 'ADMIN_PROPOSAL_SUBMITTED_PAID',
  ADMIN_PROPOSAL_BECAME_PAID: 'ADMIN_PROPOSAL_BECAME_PAID',
  ADMIN_REUPLOAD_SUBMITTED: 'ADMIN_REUPLOAD_SUBMITTED',

  // Policy - user
  POLICY_ISSUED: 'POLICY_ISSUED',
  MOTOR_REG_NO_UPLOAD_REMINDER: 'MOTOR_REG_NO_UPLOAD_REMINDER',
  POLICY_EXPIRING_D30: 'POLICY_EXPIRING_D30',
  POLICY_EXPIRING_D15: 'POLICY_EXPIRING_D15',
  POLICY_EXPIRING_D5: 'POLICY_EXPIRING_D5',
  POLICY_EXPIRING_D1: 'POLICY_EXPIRING_D1',
  POLICY_EXPIRED: 'POLICY_EXPIRED',

  // Policy - admin
  ADMIN_MOTOR_REG_NO_UPLOADED: 'ADMIN_MOTOR_REG_NO_UPLOADED',
  ADMIN_POLICY_EXPIRING_D30: 'ADMIN_POLICY_EXPIRING_D30',
  ADMIN_POLICY_EXPIRING_D15: 'ADMIN_POLICY_EXPIRING_D15',
  ADMIN_POLICY_EXPIRING_D5: 'ADMIN_POLICY_EXPIRING_D5',
  ADMIN_POLICY_EXPIRING_D1: 'ADMIN_POLICY_EXPIRING_D1',
  ADMIN_POLICY_EXPIRED: 'ADMIN_POLICY_EXPIRED',

  // Claims (motor only)
  CLAIM_SUBMITTED: 'CLAIM_SUBMITTED',
  CLAIM_REUPLOAD_REQUIRED: 'CLAIM_REUPLOAD_REQUIRED',
  CLAIM_APPROVED: 'CLAIM_APPROVED',
  CLAIM_REJECTED: 'CLAIM_REJECTED',
  ADMIN_NEW_CLAIM: 'ADMIN_NEW_CLAIM',
  ADMIN_CLAIM_REUPLOAD_SUBMITTED: 'ADMIN_CLAIM_REUPLOAD_SUBMITTED',

  // Renewal (motor only)
  RENEWAL_DOCUMENT_SENT: 'RENEWAL_DOCUMENT_SENT',

  // Refund
  REFUND_STATUS_UPDATED: 'REFUND_STATUS_UPDATED',
  REFUND_PROCESSED: 'REFUND_PROCESSED',
  REFUND_CASE_CLOSED: 'REFUND_CASE_CLOSED',
  ADMIN_REFUND_ACTION_REQUIRED: 'ADMIN_REFUND_ACTION_REQUIRED',

  // Support
  SUPPORT_TICKET_REPLY: 'SUPPORT_TICKET_REPLY',
  SUPPORT_TICKET_CREATED: 'SUPPORT_TICKET_CREATED',
  ADMIN_SUPPORT_TICKET_CREATED: 'ADMIN_SUPPORT_TICKET_CREATED',
  ADMIN_SUPPORT_TICKET_REPLY: 'ADMIN_SUPPORT_TICKET_REPLY',

  // Welcome
  USER_WELCOME_EMAIL: 'USER_WELCOME_EMAIL',
};
